# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build and Test Teeko Game

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cc: gcc
          - os: macos-latest
            cc: gcc

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
          echo "CFLAGS=-Wall -Wextra -I./include" >> $GITHUB_ENV

      - name: Build
        run: make

      - name: Test
        run: |
          if [ -f "build/teeko" ]; then
            echo "Build successful, binary exists"
          else
            echo "Build failed, binary not found"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: teeko-binary-${{ matrix.os }}
          path: build/teeko
